version: '3.4'

services:
  walletapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AuthSettings__RefreshExpiryInDays=${AuthSettings__RefreshExpiryInDays}
      - ConnectionStrings__AuthenticationDb=${ConnectionStrings__AuthenticationDb}
      - ConnectionStrings__WalletDb=${ConnectionStrings__WalletDb}
      - UseCORS=${UseCORS}
      - EFCreateDatabase=${EFCreateDatabase}
      - LoginProvider=${LoginProvider}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  wallet-db:
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}